---
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
type: Opaque
data:
  JWT_SECRET: 'cDRzdGEudzF0aC1iMGxvZ240ZTMtc0B1Y2U='
  JWT_ALGO: 'UlMyNTY='
  DATABASE_URL: 'bXlzcWw6Ly9zYWNoaW50aGE6QWRtaW5AMTIzQGF1dGhkYnNlcnZlci5teXNxbC5kYXRhYmFzZS5henVyZS5jb20vYXV0aF9kZXY/c3NsYWNjZXB0PU5v'
  NODE_ENV: 'cHJvZHVjdGlvbg=='
  COOKIE_SECRET: 'ODIzRkQ4N0U4QjM3NTg2NA=='
  JWT_ACCESS_TOKEN_PRIVATE_KEY: 'LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlCT1FJQkFBSkJBSjdVblpyNUxpUGJxbDRENlo3VHVKK2NFMkI0Y3FzbnUzeUJaUHo2NmtqZDhJT1RFdjlNCkpEdmhMQ05PczYyWHBZcmFZYU5HS3UrN3Q4YVVjcWNoRzJNQ0F3RUFBUUpBRS84YXRKY29tdlVkOXVZeE5JRGQKWHFMc3dabUlma25yVGRxUWwxVVR5QWFPRWpIRGFnR0lGdEhRZE5IZTAybkp6a2Z1WkdWSkJVRmo1aTJJVyszMQpxUUloQU9LQVRxOVpSZHR0T0JDWWJLR3VpbjZnd1FVZ2YzUGkwSjh3Snh3cjNRVDFBaUVBczRRZ0lhR1c1V3NaCmNqWUQ3bVpwcXBiRkdubnBvMVR6QU1YS2psQ2dKL2NDSUQyZVZFbWx5cmhnSlNGMnBnN3lNZUV6RUcrNW9KTEIKUUtvZDZuWGloUFZGQWlCY0ZuUXhMR1p1NjhEUzhOaVZiQjNhYjV0TzJLazhxekE0L2ozSlFaeld3d0lnU2N1awoyZWlBM3E5ci9EdDQ3OUZHek4xSEVSdzJ2TXZjeEV6REZWRnV5aDg9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t'
  JWT_ACCESS_TOKEN_PUBLIC_KEY: 'LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZ3d0RRWUpLb1pJaHZjTkFRRUJCUUFEU3dBd1NBSkJBSjdVblpyNUxpUGJxbDRENlo3VHVKK2NFMkI0Y3Fzbgp1M3lCWlB6NjZramQ4SU9URXY5TUpEdmhMQ05PczYyWHBZcmFZYU5HS3UrN3Q4YVVjcWNoRzJNQ0F3RUFBUT09Ci0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQ=='
  JWT_REFRESH_TOKEN_PRIVATE_KEY: 'LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlCT0FJQkFBSkFmTmJzOVJhUGNnVG5RalB4cExLUXkvRHdBSVh5NFNiUWdlejFNU2pwWnozQ0tsTXdpWWwyCm5IUVg5Rk5NcU1pMmxnL29yUjJDTUJxRzFNdnlvN1EyTVFJREFRQUJBa0FKUStwU1JscGZHLzRONjgwRGJEMVMKNVk3cWV3YUxyMVhLVHN2ajJpVjRoQUdxb0d3K3NvbEZUalp1Y21xaW9vY1cydTNXYVdxdkNrVmtvamc2OFFBQgpBaUVBNElqNkFXbG91am84T1YvSEJ3elZpaDQzRllCNEpkZnd3SjFwYTBRVFlWRUNJUUNPVlhMdGZOTFh3cXFlCndZNVIrWktwY3JBb0tBMjVYM3M1cEhVNFhYVk80UUlnSDM0VzBxdmVMSUNPZ2QyVkpNQUFFMmM1Z3FLS040U2EKRituOEp6ZGRJSUVDSUZ4SllUeEU2L3lEdHRjNnpzbXVGWDhTNHM4V3NWZFpabStJaDR5bFpGTmhBaUFGRWJwSApqdlZqSHlPdlIyQ2F1clFmTmU3QldWVnVlODNQN3pYSXV3eHl5Zz09Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t'
  JWT_REFRESH_TOKEN_PUBLIC_KEY: 'LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZzd0RRWUpLb1pJaHZjTkFRRUJCUUFEU2dBd1J3SkFmTmJzOVJhUGNnVG5RalB4cExLUXkvRHdBSVh5NFNiUQpnZXoxTVNqcFp6M0NLbE13aVlsMm5IUVg5Rk5NcU1pMmxnL29yUjJDTUJxRzFNdnlvN1EyTVFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0t'
  PORT: 'MzAwMA=='
  LOG_LEVEL: 'ZGVidWc='
  SECRET_KEY: 'MjEwOTg3NjU0MzIxMDk4NzY1NDMyMTA5ODc2NTQzMjE='
  ENCRYPTION_KEY: 'YjRhZWMyNzQ4ZDkxZjI4ZjZhODEyYzYwNjFjYTFhYWEzZDMyZDE2OWVkYmYyMWQzODdkNjQzNmViOGM3MGVmNw=='
  USER_ENCRYPTION_KEY: 'ZDQzNjVjYmJkNGYzYmExOTVlMTI5YmIwZjIyYzgyYjE1NTM2MmYwYjc4NTU4N2FiZGUyOWNkNTQxZTcwOWUxMA=='
  USER_IV: 'OWQ1NDQ5NTZiMjRkYTBkMTE5OTk1MzU1MGYzNzYxNGU='
  REDIS_URL : 'redis://default:HyOciXNdF3en5lPuudx2dw5OSR4b7dVRGAzCaEceKFQ=@redis-authserver.redis.cache.windows.net:17352'
  REDIS_HOST : 'authserver.redis.cache.windows.net'
  REDIS_PORT : 6380
  REDIS_PASSWORD : 'HyOciXNdF3en5lPuudx2dw5OSR4b7dVRGAzCaEceKFQ='

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service-container
          image: sachinthadev/auth_service:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: DATABASE_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-service
spec:
  selector:
    app: auth_service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
